### ISSUE TITLE
Need the ability to filter all the shop carts with a specific product

### ISSUE THREAD

**Issue by XinpingHuangE** [DevopsShopcarts/shopcarts#38]
**As a**  administrator 
 **I need** to find all shopcarts with a specific product  
 **So that** I can get a list of carts if I need to take an action for carts with a product
   
 ### Details and Assumptions
 * The API should be RESTful
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given many shopcarts each with some items
 When administrator finds shopcart with a specific product in query string
 Then a list of shopcarts that contain the product is returned.
 ```

**Comment by AntonioTan** [comment]
Hello, guys, when I was working on this issue, I had a problem with the model design. In current design, the id of product is the primary key. And each product will have a shopcart_id. But in fact, one kind of product can be added to many shopcarts. The problem is how we can filter shopcarts with a given product. We should filter by the product id or the name? if we filter by product id, in current design, the same product in real world has many ids in our database if this product is added to different shopcarts. Need help here.
